services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod    
    ports:
      - "8445:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped