FROM node:20.5.0-alpine3.18 as build-stage

WORKDIR /app/
COPY package*.json .
RUN npm install
COPY . .
RUN ["npm", "run", "build"]

FROM nginx:1.25.1-alpine3.17-slim
COPY --from=build-stage /app/dist /usr/share/nginx/html
#COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]