services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod    
    ports:
      - "8445:443"  # Mantenemos este mapeo
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped