services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod    
    ports:
      - "443:443"  # Cambiado de "8445:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped