# services:
#   vite-app2:
#     build: .
#     ports:
#       - '5174:5174'
#     volumes:
#       - .:/app
#       - /app/node_modules
#     environment:
#       - CHOKIDAR_USEPOLLING=true

services:
  vite-app:
    build: .
    ports:
      - '82:82'