FROM node:20.5.0-alpine3.18 as build-stage

WORKDIR /app/
COPY package*.json .
RUN npm install
COPY . .
RUN ["npm", "run", "build"]

# Etapa final
FROM nginx:alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
# El EXPOSE 443 se elimina ya que nginx:alpine ya lo incluye
